import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import './style.css';
import './ascii.css';

pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
type Evidence={page:number;printed_page:string;kind:string;quote:string};
type Pin={number:string;original_name:string;symbol_name:string;electrical_type:string;group:string;part:string;position:string;kind:string;fact:string;observation:string;issues:string[];evidence:Evidence[]};
type RecordPin={raw:Pin;edits:Partial<Pin>;review:string;conflicts:string[];versions:Pin[]};
type Candidate={model:string;package:string;pin_count:number|null;fact:string;observation:string;evidence:Evidence[]};
type Job={id:string;stage:string;status:string;batches:{pages:number[];status:string;error:string;audit?:unknown;duration?:number}[]};
type Project={id:string;name:string;demo:boolean;page_count:number;revision:number;target:Candidate|null;candidates:Candidate[];pins:{[key:string]:RecordPin};parts:string[];jobs:Job[];relevant_pages:number[];history:unknown[]};
const types=['Unknown','Input','Output','Bidirectional','Passive','Power','Open Collector','Open Emitter','3-State'];
const positions=['Left','Right','Top','Bottom'];
const effective=(r:RecordPin):Pin=>({...r.raw,...r.edits});
let mutationTail:Promise<unknown>=Promise.resolve();
const revisions:Record<string,number>={};
function api(path:string,method='GET',body?:unknown):Promise<any>{
 const send=async()=>{
  const id=path.match(/^\/projects\/([^/]+)/)?.[1];
  const payload=body&&!(body instanceof FormData)&&typeof body==='object'&&'revision'in body&&id&&revisions[id]!==undefined?{...body,revision:revisions[id]}:body;
  const response=await fetch('/api'+path,{method,headers:payload instanceof FormData?{}:{'Content-Type':'application/json'},body:payload instanceof FormData?payload:payload===undefined?undefined:JSON.stringify(payload)});
  if(!response.ok){let error;try{error=await response.json()}catch{error={detail:response.statusText}} throw new Error(typeof error.detail==='string'?error.detail:JSON.stringify(error.detail));}
  const result=await response.json();
  if(result.id&&typeof result.revision==='number')revisions[result.id]=Math.max(revisions[result.id]??0,result.revision);
  return result;
 };
 if(method==='GET')return send();
 const result=mutationTail.catch(()=>{}).then(send);mutationTail=result;return result;
}

function PdfReader({project,page,setPage}:{project:Project;page:number;setPage:(p:number)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null);const [doc,setDoc]=useState<pdfjs.PDFDocumentProxy|null>(null);const [zoom,setZoom]=useState(1);const [query,setQuery]=useState('');const [hits,setHits]=useState<number[]>([]);const [error,setError]=useState('');const [searching,setSearching]=useState(false);
 useEffect(()=>{setDoc(null);setHits([]);setError('');const task=pdfjs.getDocument('/api/projects/'+project.id+'/pdf');task.promise.then(setDoc).catch(e=>setError(String(e)));return()=>{void task.destroy()}},[project.id]);
 useEffect(()=>{if(!doc)return;let cancelled=false;let render:pdfjs.RenderTask|undefined;
  doc.getPage(page).then(p=>{if(cancelled||!canvas.current)return;const viewport=p.getViewport({scale:zoom});const c=canvas.current;c.width=viewport.width*devicePixelRatio;c.height=viewport.height*devicePixelRatio;c.style.width=viewport.width+'px';c.style.height=viewport.height+'px';render=p.render({canvas:c,viewport,transform:[devicePixelRatio,0,0,devicePixelRatio,0,0]});return render.promise}).catch(e=>{if(e.name!=='RenderingCancelledException')setError(String(e))});return()=>{cancelled=true;render?.cancel()}
 },[doc,page,zoom]);
 async function search(){if(!doc||!query)return;setSearching(true);const found:number[]=[];try{for(let n=1;n<=doc.numPages;n++){const text=await(await doc.getPage(n)).getTextContent();if(text.items.map(x=>'str'in x?x.str:'').join(' ').toLowerCase().includes(query.toLowerCase()))found.push(n)}setHits(found);if(found.length)setPage(found[0]);}finally{setSearching(false)}}
 return <section className="pdf panel"><div className="panel-title"><span>01 / 原始手册</span><span className="badge">PDF 文件页序</span></div><div className="toolbar"><button disabled={page<=1} onClick={()=>setPage(page-1)}>←</button><input aria-label="PDF 页码" type="number" min="1" max={project.page_count} value={page} onChange={e=>setPage(Math.min(project.page_count,Math.max(1,+e.target.value)))}/><span>/ {project.page_count}</span><button disabled={page>=project.page_count} onClick={()=>setPage(page+1)}>→</button><select aria-label="缩放" value={zoom} onChange={e=>setZoom(+e.target.value)}>{[.6,.8,1,1.25,1.5,2].map(n=><option key={n} value={n}>{n*100}%</option>)}</select></div><div className="toolbar"><input placeholder="搜索 PDF 文本层" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}}/><button onClick={()=>void search()} disabled={searching}>{searching?'搜索中':'搜索'}</button></div>{query&&<div className="search-results">{hits.length?hits.map(n=><button key={n} onClick={()=>setPage(n)}>第 {n} 页</button>):'无匹配；扫描 PDF 可能没有可搜索文本层'}</div>}<div className="paper">{error?<p className="error">{error}</p>:<canvas ref={canvas}/>}</div><footer>证据默认按页面定位 · 不生成未经验证的区域框</footer></section>
}

function SymbolPreview({project}:{project:Project}){
 const groupKey=(p:Pin)=>{const n=p.symbol_name||p.original_name;if(p.kind==='NC'||p.kind==='DNC')return 0;if(/(GND|VSS)/i.test(n))return 1;if(/^(VCC|VDD|AVCC|VCCO|VBATT|VREF|VIN)/i.test(n))return 2;if(/^(CLK|XTAL|OSC|SCK|SCL)/i.test(n))return 3;if(/^(RESET|EN|CS|OE|WE|RE|IRQ|INT)/i.test(n))return 4;if(p.electrical_type==='Output')return 5;if(p.electrical_type==='Bidirectional')return 6;return 7};
 const pins=Object.values(project.pins).map(effective).filter(p=>p.kind!=='mechanical').sort((a,b)=>groupKey(a)-groupKey(b)||a.number.localeCompare(b.number,undefined,{numeric:true}));
 return <div className="symbols">{project.parts.map(part=>{const list=pins.filter(p=>p.part===part);const count=(side:string)=>list.filter(p=>p.position===side).length;const h=Math.max(180,Math.max(count('Left'),count('Right'))*28+65);const w=Math.max(340,Math.max(count('Top'),count('Bottom'))*100+60);return <div key={part} className="symbol"><div className="panel-title">Part {part} <span>{list.length} pins · Visibility 1 / Line</span></div><svg role="img" aria-label={'Part '+part+' 符号预览'} viewBox={`0 0 ${w+160} ${h+160}`}><rect x="80" y="80" width={w} height={h} rx="3" fill="#f6faf9" stroke="#54877d" strokeWidth="2"/><text x={80+w/2} y={80+h/2} textAnchor="middle" className="part-label">U?{part}</text>{positions.flatMap(side=>list.filter(p=>p.position===side).map((p,i)=>{const vertical=side==='Top'||side==='Bottom';const x=vertical?100+(i+.5)*(w-40)/count(side):side==='Left'?80:w+80;const y=vertical?side==='Top'?80:h+80:110+i*28;const dx=side==='Left'?-35:side==='Right'?35:0;const dy=side==='Top'?-35:side==='Bottom'?35:0;return <g key={p.number}><line x1={x} y1={y} x2={x+dx} y2={y+dy} stroke="#286b61" strokeWidth="2"/><text x={x+dx} y={y+dy-6} fontSize="11" textAnchor="middle">{p.number}</text><text x={x+(side==='Left'?8:side==='Right'?-8:0)} y={y+(side==='Top'?14:side==='Bottom'?-8:4)} fontSize="11" textAnchor={vertical?'middle':side==='Left'?'start':'end'}>{p.symbol_name}</text></g>}))}</svg></div>})}</div>
}

function AsciiOrcadTool(){
 const [file,setFile]=useState<File|null>(null);const [maxPins,setMaxPins]=useState(100);const [useAi,setUseAi]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [ai,setAi]=useState({configured:false,provider:'',model:''});const [aiForm,setAiForm]=useState({provider:'DeepSeek',base_url:'https://api.deepseek.com/v1',model:'deepseek-chat',api_key:''});const [aiStatus,setAiStatus]=useState<{ok:boolean;text:string}|null>(null);
 useEffect(()=>{void api('/config').then(r=>setAi({configured:r.ascii?.configured??r.configured,provider:r.ascii?.provider||r.provider,model:r.ascii?.model||r.model})).catch(()=>{})},[]);
 async function saveAi(){setAiStatus(null);setBusy(true);try{const result=await api('/ai/config','POST',aiForm);setAi({configured:true,provider:result.provider||aiForm.provider,model:result.model||aiForm.model});setAiStatus({ok:true,text:'已连接 '+aiForm.provider+' · '+aiForm.model})}catch(e){setAiStatus({ok:false,text:(e as Error).message})}finally{setBusy(false)}}
 async function convert(){
  if(!file){setMessage('请先选择 AMD/Xilinx ASCII Pinout 文件。');return}
  setBusy(true);setMessage('');
  try{
   const form=new FormData();form.append('file',file);form.append('max_pins_per_section',String(maxPins));form.append('use_ai',String(useAi));
   const response=await fetch('/api/orcad/ascii/convert',{method:'POST',body:form});
   if(!response.ok){const x=await response.json();throw new Error(x.detail||'转换失败')}
   const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=(file.name.replace(/\.[^.]+$/,'')||'XILINX_FPGA')+'_OrCAD_Pinlist.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);
   setMessage('已下载。工作簿内含 Paste_To_OrCAD、Section_Summary 和 Source_Audit 三个工作表。');
  }catch(e){setMessage((e as Error).message)}finally{setBusy(false)}
 }
 return <section className="ascii-tool panel"><div className="panel-title"><span>FPGA ASCII Pinout → OrCAD</span><span className="badge">AMD / Xilinx</span></div><div className="ascii-body"><p>读取官方 ASCII Pinout，按 Bank、配置、控制、电源、GND 自动拆分 Section。每个 Section 最多 100 脚，重复的 GND 会自动继续拆到下一个 Part。</p><div className="ascii-controls"><input type="file" accept=".txt,.pin,.rpt,text/plain" onChange={e=>{setFile(e.target.files?.[0]||null);setMessage('')}}/><label>最大脚数 <input aria-label="每个 Section 的最大脚数" type="number" min="1" max="100" value={maxPins} onChange={e=>setMaxPins(Math.max(1,Math.min(100,+e.target.value||100)))}/></label><button className="primary" disabled={busy} onClick={()=>void convert()}>生成 OrCAD Excel</button></div><label className="ai-toggle"><input type="checkbox" checked={useAi} disabled={!ai.configured} onChange={e=>setUseAi(e.target.checked)}/>对控制/模拟等模糊引脚使用 AI 分类建议（复用当前 {ai.provider||'后端'} API，模型：qwen-plus）</label><details className="ai-config"><summary>AI 分类设置（可选，仅用于模糊引脚建议）</summary><div className="ai-form"><select aria-label="AI 供应商" value={aiForm.provider} onChange={e=>{const provider=e.target.value;setAiForm({...aiForm,provider,base_url:provider==='DeepSeek'?'https://api.deepseek.com/v1':'',model:provider==='DeepSeek'?'deepseek-chat':''})}}><option value="DeepSeek">DeepSeek</option><option value="OpenAI-compatible">OpenAI-compatible（自定义）</option></select><input placeholder="Base URL（https:// 开头）" value={aiForm.base_url} onChange={e=>setAiForm({...aiForm,base_url:e.target.value})}/><input placeholder="模型名" value={aiForm.model} onChange={e=>setAiForm({...aiForm,model:e.target.value})}/><input type="password" placeholder="API Key" autoComplete="off" value={aiForm.api_key} onChange={e=>setAiForm({...aiForm,api_key:e.target.value})}/><button disabled={busy||!aiForm.base_url||!aiForm.model||!aiForm.api_key} onClick={()=>void saveAi()}>{busy?'连接中…':'保存并测试'}</button></div>{aiStatus&&<small className={'ai-status '+(aiStatus.ok?'ok':'err')}>{aiStatus.text}</small>}<small>{ai.configured?'当前已配置 '+ai.provider+'（'+ai.model+'）。':''}密钥仅保存在后端进程内存，重启后需重新配置；留空则继续用确定性规则，不调用 AI。</small></details>{message&&<div className={message.startsWith('已下载')?'ascii-message ok':'ascii-message'}>{message}</div>}</div></section>
}

function VisionConfig(){
 const [models,setModels]=useState<{name:string;base_url:string;model:string;has_key:boolean}[]>([]);const [current,setCurrent]=useState('');const [form,setForm]=useState({name:'',base_url:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen3-vl-plus',api_key:''});const [status,setStatus]=useState<{ok:boolean;text:string}|null>(null);const [busy,setBusy]=useState(false);const [fetched,setFetched]=useState<string[]>([]);
 useEffect(()=>{void api('/models').then(ms=>{setModels(ms);if(ms.length)setCurrent(ms[0].name)}).catch(()=>{})},[]);
 async function saveModel(){setBusy(true);setStatus(null);try{const ms=await api('/models','POST',form);setModels(ms);setCurrent(form.name);setStatus({ok:true,text:'已保存并启用 '+form.name});setForm({...form,api_key:''})}catch(e){setStatus({ok:false,text:(e as Error).message})}finally{setBusy(false)}}
 async function useModel(name:string){setBusy(true);setStatus(null);try{await api('/models/select','POST',{name});setCurrent(name);setStatus({ok:true,text:'已切换到 '+name})}catch(e){setStatus({ok:false,text:(e as Error).message})}finally{setBusy(false)}}
 async function delModel(name:string){setBusy(true);setStatus(null);try{const ms=await api('/models/'+encodeURIComponent(name),'DELETE');setModels(ms);if(current===name)setCurrent(ms[0]?.name||'');setStatus({ok:true,text:'已删除 '+name})}catch(e){setStatus({ok:false,text:(e as Error).message})}finally{setBusy(false)}}
 async function fetchList(){setBusy(true);setStatus(null);try{const r=await api('/models/fetch','POST',{base_url:form.base_url,api_key:form.api_key});const list=r.models||[];setFetched(list);if(list.length)setForm(f=>({...f,model:list[0]}));setStatus({ok:true,text:'获取到 '+list.length+' 个模型，请从列表选择'})}catch(e){setStatus({ok:false,text:(e as Error).message})}finally{setBusy(false)}}
 return <details className="vision-config"><summary>模型配置（云端识别，密钥加密保存在本机）</summary>{models.length>0&&<div className="model-list">{models.map(m=><div key={m.name} className={'model-item'+(m.name===current?' active':'')}><span>{m.name}<small>{m.model}</small></span><button disabled={busy||m.name===current} onClick={()=>void useModel(m.name)}>{m.name===current?'使用中':'使用'}</button><button disabled={busy} onClick={()=>void delModel(m.name)}>删</button></div>)}</div>}<div className="ai-form"><input placeholder="模型名称（如 百炼/智谱）" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Base URL（https:// 开头）" value={form.base_url} onChange={e=>setForm({...form,base_url:e.target.value})}/><input type="password" placeholder="API Key" autoComplete="off" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})}/>{fetched.length>0?<select value={form.model} onChange={e=>setForm({...form,model:e.target.value})}>{fetched.map(m=><option key={m} value={m}>{m}</option>)}</select>:<input placeholder="模型 ID" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/>}<button disabled={busy||!form.base_url||!form.api_key} onClick={()=>void fetchList()}>{busy?'获取中…':'获取模型列表'}</button><button disabled={busy||!form.name||!form.base_url||!form.model||!form.api_key} onClick={()=>void saveModel()}>{busy?'保存中…':'保存并启用'}</button></div>{status&&<small className={'ai-status '+(status.ok?'ok':'err')}>{status.text}</small>}<small>密钥加密存储在本机 data 目录，重启后自动加载，无需重复输入。不配置也可使用上传、编辑、导出和 ASCII 转换。</small></details>;
}

function Benchmark(){
 const [projects,setProjects]=useState<{id:string;name:string;demo:boolean}[]>([]);const [models,setModels]=useState<{name:string;model:string}[]>([]);const [form,setForm]=useState({project:'',stage:'extract',pages:'',models:[] as string[]});const [results,setResults]=useState<any[]|null>(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');
 useEffect(()=>{void api('/projects').then(setProjects).catch(()=>{});void api('/models').then(setModels).catch(()=>{})},[]);
 function parsePages(s:string){if(!s.trim())return [];const r:number[]=[];for(const t of s.split(/[,，\s]+/)){if(!/^\d+(-\d+)?$/.test(t))throw new Error('页码格式：1-4,8');const [a,b]=t.split('-').map(Number);for(let n=a;n<=(b??a);n++)r.push(n)}return r}
 async function run(){setBusy(true);setResults(null);setStatus('');try{const res=await api('/benchmark','POST',{project_id:form.project,stage:form.stage,pages:parsePages(form.pages),models:form.models});setResults(res.results)}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}
 function toggle(m:string){setForm(f=>f.models.includes(m)?{...f,models:f.models.filter(x=>x!==m)}:{...f,models:[...f.models,m]})}
 return <details className="benchmark"><summary>模型速度对比（并发解析多个模型）</summary><p className="bench-hint">选一个已上传的项目、页码范围，勾选多个模型，同时并发解析并对比耗时与结果数。</p><div className="bench-form"><select value={form.project} onChange={e=>setForm({...form,project:e.target.value})}><option value="">选择项目</option>{projects.filter(x=>!x.demo).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}><option value="extract">提取（需已确认目标）</option><option value="scan">扫描候选</option></select><input placeholder="页码，如 1-4（留空=全部/定位页）" value={form.pages} onChange={e=>setForm({...form,pages:e.target.value})}/></div><div className="bench-models">{models.map(m=><label key={m.name} className="bench-chk"><input type="checkbox" checked={form.models.includes(m.name)} onChange={()=>toggle(m.name)}/>{m.name}<small>{m.model}</small></label>)}</div><button className="primary" disabled={busy||!form.project||form.models.length===0} onClick={()=>void run()}>{busy?'解析中…':'开始对比'}</button>{status&&<div className="ascii-message">{status}</div>}{results&&<div className="bench-results">{results.map((r,i)=><div key={i} className="bench-row"><span className="rank">#{i+1}</span><b>{r.model}</b><small>{r.model_id}</small>{r.error?<span className="bench-err">✗ {r.error}</span>:<><span className="bench-time">{r.duration}s</span><span>{r.count!=null?r.count+' 项':''}</span><span>{r.tokens?r.tokens+' tokens':''}</span></>}</div>)}</div>}</details>;
}

function App(){
 const [projects,setProjects]=useState<{id:string;name:string;demo:boolean;status:string}[]>([]);const [p,setP]=useState<Project|null>(null);const [config,setConfig]=useState({configured:false,model:'',provider:''});const [page,setPage]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [focus,setFocus]=useState<string|null>(null);const [filter,setFilter]=useState('');const [onlyPending,setOnlyPending]=useState(false);const [tab,setTab]=useState('table');const [pages,setPages]=useState('');const [partName,setPartName]=useState('');const [batchField,setBatchField]=useState('part');const [batchValue,setBatchValue]=useState('');const [checks,setChecks]=useState<string[]>([]);const [newNumber,setNewNumber]=useState('');const [manual,setManual]=useState({model:'',package:'',pin_count:''});const [showHistory,setShowHistory]=useState(false);
 const uploadRef=useRef<HTMLInputElement>(null);const importRef=useRef<HTMLInputElement>(null);
 const loadList=()=>api('/projects').then(setProjects);
 useEffect(()=>{void loadList();api('/config').then(setConfig).catch(e=>setError(e.message))},[]);useEffect(()=>{const id=setInterval(()=>{void loadList()},2500);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!p?.jobs.some(j=>j.status==='running'))return;const id=setInterval(()=>api('/projects/'+p.id).then(setP).catch(e=>setError(e.message)),1600);return()=>clearInterval(id)},[p?.id,p?.jobs]);
 async function action(fn:()=>Promise<Project|void>){setBusy(true);setError('');try{const result=await fn();if(result)setP(result)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function open(project:Project){setP(project);setPage(1);setSelected([]);setFocus(null);setPages('');setChecks([])}
 async function upload(file:File|undefined,importing=false){if(!file)return;const f=new FormData();f.append('file',file);await action(async()=>{open(await api(importing?'/import':'/projects','POST',f));await loadList()})}
 async function uploadBatch(files:FileList|null){if(!files||files.length===0)return;setBusy(true);setError('');try{for(const file of Array.from(files)){const f=new FormData();f.append('file',file);open(await api('/projects','POST',f));await loadList()}}catch(e){setError((e as Error).message)}finally{setBusy(false);await loadList()}}
 const statusLabel=(s:string)=>({new:'待扫描',scanning:'扫描中…',extracting:'提取中…',pending_target:'待确认目标',pending_extract:'待提取',pending_review:'待审核',done:'已完成'} as Record<string,string>)[s]||s;
 function parsePages(){if(!pages.trim())return [];const result:number[]=[];for(const token of pages.split(/[,，\s]+/)){if(!/^\d+(-\d+)?$/.test(token))throw new Error('页码格式示例：1-4,8,10');const [a,b]=token.split('-').map(Number);if((b??a)<a||(b??a)-a>2000)throw new Error('页码范围无效');for(let n=a;n<=(b??a);n++)result.push(n)}return result}
 function run(stage:string){void action(()=>api(`/projects/${p!.id}/runs`,'POST',{stage,pages:parsePages()}))}
 function edit(numbers:string[],values:object){void action(()=>api(`/projects/${p!.id}/pins`,'PATCH',{revision:p!.revision,numbers,values}))}
 function editField(number:string,key:string,value:string){const current=effective(p!.pins[number]) as unknown as Record<string,string>;if(current[key]!==value)edit([number],{[key]:value})}
 const record=focus&&p?.pins[focus];const entries=p?Object.entries(p.pins).filter(([,r])=>{const q=effective(r);return (!onlyPending||r.review!=='confirmed')&&[q.number,q.symbol_name,q.part].some(v=>v.toLowerCase().includes(filter.toLowerCase()))}):[];
 async function download(kind:string){if(!p)return;setError('');try{await mutationTail;const response=await fetch(`/api/projects/${p.id}/export/${kind}`);if(!response.ok){const x=await response.json();throw new Error(x.detail)}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;const base=(p.target?.model||p.name.replace(/\.pdf$/i,'')).replace(/[\\/:*?"<>|]/g,'').trim()||'datasheet';a.download=`${p.demo?'DEMO-':''}${base}.${kind}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}catch(e){setError((e as Error).message)}}
 const quit=()=>{if(!window.confirm('确定退出应用？后台服务将停止。'))return;const bridge=(window as Window & {pywebview?:{api?:{quit?:()=>Promise<boolean>}}}).pywebview?.api;if(bridge?.quit){void bridge.quit()}else{void fetch('/api/shutdown',{method:'POST'})}}
 return <><header className="app-header"><div className="brand"><span className="brand-icon"><svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2" fill="none" stroke="currentColor" strokeWidth="1.6"/><path d="M3 9h3M3 15h3M18 9h3M18 15h3M9 3v3M15 3v3M9 18v3M15 18v3" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/></svg></span><div>Datasheet<span>2</span>Symbol<small>DATASHEET REVIEW WORKSPACE</small></div></div><div className="header-actions"><span className={'connection '+(config.configured?'ready':'')}>{config.configured?'● '+(config.provider||'AI')+' 已配置':'○ AI 未配置'} · {config.model||'未配置'}</span><button onClick={()=>importRef.current?.click()}>打开项目 JSON</button><button className="primary" onClick={()=>uploadRef.current?.click()}>＋ 上传 PDF</button><button onClick={quit}>退出</button></div></header>
 <input hidden ref={uploadRef} type="file" accept="application/pdf" multiple onChange={e=>{void uploadBatch(e.target.files);e.target.value=''}}/><input hidden ref={importRef} type="file" accept="application/json" onChange={e=>{void upload(e.target.files?.[0],true);e.target.value=''}}/>
 <div className="workspace"><aside className="sidebar"><div className="side-label">工作区 / WORKSPACE</div><button className="project" onClick={()=>setShowHistory(v=>!v)}><span>🕘</span><span>历史项目<small>{projects.length>0?`${projects.length} 个已保存项目 · 点击展开`:'暂无已保存项目'}</small></span></button>{showHistory&&<div className="history-list">{projects.length===0&&<p className="history-empty">暂无历史项目</p>}{projects.map(x=><button className={p?.id===x.id?'project active':'project'} key={x.id} onClick={()=>void action(async()=>{open(await api('/projects/'+x.id));setShowHistory(false)})}><span>▤</span><span>{x.name}<small>{x.demo?'模拟 · '+statusLabel(x.status):statusLabel(x.status)}</small></span></button>)}</div>}<div className="side-label demo-label">说明</div><div className="side-note">手册解析通过已配置的视觉模型完成。<br/>密钥加密保存在本机，不进入浏览器。</div><div className="side-label" style={{marginTop:'28px'}}>导出教程</div><div className="side-note">1. 确认封装并提取引脚<br/>2. 审核每个引脚状态<br/>3. 点击"导出 Excel ↗"<br/>4. 下载含 Pins/Reference/History 三表</div></aside>
 <main>{error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')}>关闭</button></div>}{!p?<div className="welcome"><div className="eyebrow">FROM DATASHEET TO VERIFIED PINS</div><h1>让每一个引脚<br/>都有据可查。</h1><p>上传器件手册，确认型号与封装，再与原文逐项核对。<br/>功能分组、多个 Part 和 Excel 导出在同一工作区完成。</p><button className="primary" onClick={()=>uploadRef.current?.click()}>上传一份 PDF 手册 →</button><div className="workflow">01 上传手册　 →　02 确认目标　 →　03 审核与预览　 →　04 导出 Excel</div><VisionConfig/><Benchmark/><AsciiOrcadTool/></div>:<><div className="project-heading"><div><div className="eyebrow">{p.demo?'SYNTHETIC DEMO / 合成演示':'LOCAL PROJECT / 本地项目'}</div><h1>{p.target?.model||p.name}</h1><p>{p.target?`${p.target.package} · ${p.target.pin_count??'未知'} pins`:'请先扫描候选，再确认准确型号与封装'} <span>· {p.page_count} 页 · 修订 {p.revision}</span></p></div><div className="header-actions"><button disabled={busy} onClick={()=>void action(()=>api(`/projects/${p.id}/undo`,'POST',{revision:p.revision}))}>撤销</button><button onClick={()=>void download('json')}>保存项目 JSON</button><button className="primary" onClick={()=>void download('xlsx')}>导出 Excel ↗</button></div></div>
 {p.demo&&<div className="notice">演示项目：引脚和 PDF 均为合成测试资料，未调用云端模型，不代表真实器件解析准确率。</div>}
 {!p.demo&&p.target&&<div className="notice" style={{background:'#eaf3ed',color:'#236f5c',borderColor:'#c5ddd2'}}>📋 <strong>导出 Excel：</strong>审核完成后点击右上角「导出 Excel ↗」，文件包含 Pins 数据表、Reference 验证表和 History 修改记录。所有脚号为文本格式，可直接复制到 Capture。</div>}
 <section className="pipeline"><div><strong>解析范围</strong><input aria-label="相关页码" placeholder={`PDF 页码，如 1-3,8；留空${p.target?'使用定位页':'扫描全部页'}`} value={pages} onChange={e=>setPages(e.target.value)}/></div><button disabled={busy||p.demo||p.jobs.some(j=>j.status==='running')} onClick={()=>run('scan')}>① 识别候选与相关页</button><button disabled={busy||p.demo||!p.target||p.jobs.some(j=>j.status==='running')} onClick={()=>run('extract')}>② 提取已确认封装</button><span>{(p.target?.pin_count||0)>=20?'引脚≥20，自动单页分批 · ':'每批 2 页 · '}同一视觉模型 · 失败可重试</span></section>
 {!p.target&&<section className="candidates panel"><h3>确认目标型号与封装</h3>{p.candidates.length===0&&<p>扫描后会在这里列出候选；也可以根据当前手册页手动指定。</p>}{p.candidates.map((c,i)=><button key={i} onClick={()=>void action(()=>api(`/projects/${p.id}/target`,'POST',{revision:p.revision,candidate:c}))}><b>{c.model}</b> / {c.package} / {c.pin_count??'?'} pins <span className="badge">{c.fact}</span> 确认 →</button>)}<div className="toolbar"><input placeholder="准确料号" value={manual.model} onChange={e=>setManual({...manual,model:e.target.value})}/><input placeholder="准确封装/连接器版本" value={manual.package} onChange={e=>setManual({...manual,package:e.target.value})}/><input placeholder="针数（可空）" type="number" value={manual.pin_count} onChange={e=>setManual({...manual,pin_count:e.target.value})}/><button disabled={!manual.model||!manual.package} onClick={()=>void action(()=>api(`/projects/${p.id}/target`,'POST',{revision:p.revision,candidate:{...manual,pin_count:manual.pin_count?+manual.pin_count:null,fact:'uncertain',observation:'用户手动指定，请对照手册确认',evidence:[{page,printed_page:'',kind:'description',quote:''}]}}))}>手动指定（依据当前页）</button></div></section>}
 {p.jobs.length>0&&<details className="jobs" open={p.jobs.some(j=>j.status!=='complete')}><summary>解析任务与用量 · {p.jobs.length} 次 · {p.jobs.at(-1)?.status}</summary>{p.jobs.map(j=>{const total=j.batches.reduce((s,b)=>s+(b.duration||0),0);return <div key={j.id}><strong>{j.stage==='scan'?'候选扫描':'引脚提取'} · {j.batches.filter(b=>b.status==='complete').length}/{j.batches.length} 批 · {j.status}{total>0&&<span className="dur"> · {total.toFixed(1)}s</span>}</strong><div className="progress"><div className="progress-bar" style={{width:(j.batches.length?Math.round(j.batches.filter(b=>b.status==='complete').length/j.batches.length*100):0)+'%'}}/></div>{j.status==='failed'&&<button onClick={()=>void action(()=>api(`/projects/${p.id}/runs/${j.id}/retry`,'POST'))}>重试失败批次</button>}{j.batches.map((b,i)=><details key={i}><summary>页 {b.pages.join(', ')} · {b.status}{b.duration!=null&&<span className="dur"> · {b.duration}s</span>} {b.error}</summary><pre>{JSON.stringify(b.audit,null,2)}</pre></details>)}</div>})}</details>}
 <div className="review-layout"><PdfReader project={p} page={page} setPage={setPage}/><section className="editor panel"><div className="panel-title"><span>02 / 引脚审核</span><span className="badge">{Object.values(p.pins).filter(r=>r.review==='confirmed').length} / {Object.keys(p.pins).length} 已确认</span></div><div className="tabs">{[['table','引脚表'],['preview','Symbol 预览'],['history','修改记录']].map(([id,label])=><button className={tab===id?'chosen':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}<button onClick={()=>void api(`/projects/${p.id}/validation`).then(x=>setChecks(x.errors)).catch(e=>setError(e.message))}>检查完整性</button><button onClick={()=>void download('tsv')}>TSV</button></div><div className="parts"><span>Parts</span>{p.parts.map(x=><span className="badge" key={x}>{x}</span>)}<input placeholder="新 Part（留空自动数字）" value={partName} onChange={e=>setPartName(e.target.value)}/><button onClick={()=>void action(async()=>{let name=partName.trim();if(!name){let n=1;while(p.parts.includes(String(n)))n++;name=String(n)}const result=await api(`/projects/${p.id}/parts`,'PUT',{revision:p.revision,parts:[...p.parts,name]});setPartName('');return result})}>＋</button></div>
 {checks.length>0&&<div className="notice">{checks.map((x,i)=><div key={i}>{x}</div>)}<small>可导出包含这些待确认状态的通用 Excel。</small></div>}
 {tab==='preview'?<SymbolPreview project={p}/>:tab==='history'?<pre className="history">{JSON.stringify(p.history,null,2)}</pre>:<><div className="toolbar"><input placeholder="筛选脚号、名称、Part" value={filter} onChange={e=>setFilter(e.target.value)}/><label><input type="checkbox" checked={onlyPending} onChange={e=>setOnlyPending(e.target.checked)}/>仅未确认</label></div><div className="toolbar"><input placeholder="补录物理脚号（字符串）" value={newNumber} onChange={e=>setNewNumber(e.target.value)}/><button disabled={busy||!newNumber.trim()} onClick={()=>void action(async()=>{const result=await api(`/projects/${p.id}/pins`,"POST",{revision:p.revision,number:newNumber,page});setNewNumber("");return result})}>补录引脚（当前页依据）</button></div><div className="batch"><span>已选 {selected.length}</span><select aria-label="批量修改字段" value={batchField} onChange={e=>{setBatchField(e.target.value);setBatchValue('')}}>{[['part','Part'],['electrical_type','电气类型'],['position','放置方向']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="批量修改值" value={batchValue} onChange={e=>setBatchValue(e.target.value)}><option value="">选择值</option>{(batchField==='part'?p.parts:batchField==='position'?positions:types).map(v=><option key={v}>{v}</option>)}</select><button disabled={!selected.length||!batchValue||busy} onClick={()=>edit(selected,{[batchField]:batchValue})}>应用</button><button disabled={!selected.length||busy} onClick={()=>edit(selected,{review:'confirmed'})}>确认选中</button></div>
 <div className="table-scroll"><table><thead><tr><th><input aria-label="选择当前筛选引脚" type="checkbox" checked={!!entries.length&&entries.every(([n])=>selected.includes(n))} onChange={e=>setSelected(e.target.checked?entries.map(([n])=>n):[])}/></th>{['脚号','原始名称','Symbol 名称','电气类型','Part','方向','结构类型','来源 / 状态'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{entries.map(([n,r])=>{const q=effective(r);return <tr key={n} className={focus===n?'focused':''} onClick={()=>{setFocus(n);setPage(q.evidence[0].page)}}><td><input aria-label={'选择引脚 '+n} type="checkbox" checked={selected.includes(n)} onChange={e=>setSelected(e.target.checked?[...selected,n]:selected.filter(x=>x!==n))}/></td><td><input className="pin-number" key={q.number} aria-label={"引脚 "+n+" 物理脚号"} defaultValue={q.number} onBlur={e=>editField(n,"number",e.target.value)}/></td><td>{q.original_name}</td><td><input key={q.symbol_name} aria-label={'引脚 '+n+' Symbol 名称'} defaultValue={q.symbol_name} onBlur={e=>editField(n,'symbol_name',e.target.value)}/></td><td><select value={q.electrical_type} onChange={e=>editField(n,'electrical_type',e.target.value)}>{types.map(v=><option key={v}>{v}</option>)}</select></td><td><select value={q.part} onChange={e=>editField(n,'part',e.target.value)}>{p.parts.map(v=><option key={v}>{v}</option>)}</select></td><td><select value={q.position} onChange={e=>editField(n,'position',e.target.value)}>{positions.map(v=><option key={v}>{v}</option>)}</select></td><td><select value={q.kind} onChange={e=>editField(n,'kind',e.target.value)}>{['electrical','NC','DNC','exposed_pad','shield','mechanical','uncertain'].map(v=><option key={v}>{v}</option>)}</select></td><td><span>p.{q.evidence.map(e=>e.page).join(',')}</span><button className={'review-status '+r.review} onClick={()=>edit([n],{review:r.review==='confirmed'?'unreviewed':'confirmed'})}>{r.review==='confirmed'?'已确认':r.review==='conflict'?'冲突待审':'待确认'}</button></td></tr>})}</tbody></table>{entries.length===0&&<div className="empty">确认封装并提取引脚后，在这里逐项核对。</div>}</div>
 {record&&<div className="evidence"><strong>引脚 {focus} · 页级依据</strong><span className="badge">{effective(record).fact}</span>{effective(record).evidence.map((e,i)=><button className="evidence-item" key={i} onClick={()=>setPage(e.page)}><b>PDF 第 {e.page} 页</b> · 印刷页 {e.printed_page||'未标注'} · {e.kind}<span>{e.quote||'未提供文字摘录，请核对原页'}</span></button>)}<p>{effective(record).observation}</p>{[...effective(record).issues,...record.conflicts].map((x,i)=><p className="conflict-text" key={i}>{x}</p>)}<details><summary>原始提取 / 人工覆盖 / 历次结果</summary><pre>{JSON.stringify(record,null,2)}</pre></details></div>}</>}
 <footer>{busy?'正在保存…':'编辑自动保存到本地 SQLite'} · Function Group 导出为空 · Excel 保留未确认状态</footer></section></div></> }</main></div></>
}
createRoot(document.getElementById('root')!).render(<App/>);
